FROM alpine

RUN echo -e "https://dl-cdn.alpinelinux.org/alpine/latest-stable/main\nhttps://dl-cdn.alpinelinux.org/alpine/latest-stable/community" >  /etc/apk/repositories
RUN apk update && apk upgrade

RUN apk add --no-cache python3 py3-pip v2ray
RUN pip3 install --break-system-packages requests

ADD --chown=root:root wireray/ /wireray
ENTRYPOINT [ "/usr/bin/python3", "/wireray/main.py" ]